server:
  port: 8380

spring:
  application:
   name : visit-service
  
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: ${DB_PASSWORD:astha123}
    url: ${JDBC_URL:jdbc:mariadb://training.csaulmmiambu.us-east-1.rds.amazonaws.com:3306/visits}
    username: ${DB_USER:admin}
   
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
        
eureka:
  client:
    register-with-eureka: true
    service-url: 
     defaultZone : ${EUREKA_SERVER:http://localhost:8761/eureka/}
  
management:
  endpoints:
    web:
      exposure:
        include: '*' 
        
logging:
  file:
    name: logs/visitdetails.log
        

          
